/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.graphic_interface;

import com.web_connector.SearchInputValidator;
import com.web_connector.UrlCreator;
import com.web_connector.WebConnector;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;

/**
 *
 * @author Kamil
 */
public class MainFrame extends javax.swing.JFrame {
    
    UrlCreator urlCreator = new UrlCreator();
    WebConnector webConnector = new WebConnector();
    SearchInputValidator searchInputValidator = new SearchInputValidator();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_radio_buttons_group = new javax.swing.ButtonGroup();
        search_input = new javax.swing.JTextField();
        download_data_button = new javax.swing.JButton();
        nip_radio_button = new javax.swing.JRadioButton();
        krs_radio_button = new javax.swing.JRadioButton();
        regon_radio_button = new javax.swing.JRadioButton();
        nazwa_radio_button = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ing KRS Szperacz - (v.Alpha Antczak Kamil)");
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        search_input.setToolTipText("Wprowadź Nip / KRS / Regon");
        search_input.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                search_inputCaretUpdate(evt);
            }
        });

        download_data_button.setText("Pobierz dane z KRS");
        download_data_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                download_data_buttonActionPerformed(evt);
            }
        });

        search_radio_buttons_group.add(nip_radio_button);
        nip_radio_button.setSelected(true);
        nip_radio_button.setText("NIP");
        nip_radio_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nip_radio_buttonMouseClicked(evt);
            }
        });
        nip_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nip_radio_buttonActionPerformed(evt);
            }
        });
        nip_radio_button.setActionCommand("conditions[krs_podmioty.nip]");

        search_radio_buttons_group.add(krs_radio_button);
        krs_radio_button.setText("KRS");
        krs_radio_button.setActionCommand("conditions[krs_podmioty.krs]");
        krs_radio_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                krs_radio_buttonMouseClicked(evt);
            }
        });

        search_radio_buttons_group.add(regon_radio_button);
        regon_radio_button.setText("REGON");
        regon_radio_button.setActionCommand("conditions[krs_podmioty.regon]");
        regon_radio_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regon_radio_buttonMouseClicked(evt);
            }
        });

        search_radio_buttons_group.add(nazwa_radio_button);
        nazwa_radio_button.setText("NAZWA DZIAŁALNOŚCI");
        nazwa_radio_button.setActionCommand("conditions[q]");
        nazwa_radio_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nazwa_radio_buttonMouseClicked(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Identyfikator Działalności");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(download_data_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(search_input, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nip_radio_button)
                                .addGap(18, 18, 18)
                                .addComponent(krs_radio_button)
                                .addGap(18, 18, 18)
                                .addComponent(regon_radio_button)
                                .addGap(18, 18, 18)
                                .addComponent(nazwa_radio_button))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nip_radio_button)
                    .addComponent(krs_radio_button)
                    .addComponent(regon_radio_button)
                    .addComponent(nazwa_radio_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(download_data_button)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Ing KRS Szperacz");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void download_data_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_download_data_buttonActionPerformed
       
        try {
            String id = webConnector.get_data(urlCreator.build_url( search_radio_buttons_group.getSelection().getActionCommand(), search_input.getText() ));
            webConnector.get_full_data(id);
            
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_download_data_buttonActionPerformed

    private void nip_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nip_radio_buttonActionPerformed
        
        if(searchInputValidator.validate_input(search_input.getText(), search_radio_buttons_group.getSelection().getActionCommand()))
            search_input.setBackground(Color.white);
        else
            search_input.setBackground(Color.orange);
    }//GEN-LAST:event_nip_radio_buttonActionPerformed

    private void search_inputCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_search_inputCaretUpdate
          
        if(searchInputValidator.validate_input(search_input.getText(), search_radio_buttons_group.getSelection().getActionCommand()))
            search_input.setBackground(Color.white);
        else
            search_input.setBackground(Color.orange);
        
    }//GEN-LAST:event_search_inputCaretUpdate

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        if(searchInputValidator.validate_input(search_input.getText(), search_radio_buttons_group.getSelection().getActionCommand()))
            search_input.setBackground(Color.white);
        else
            search_input.setBackground(Color.orange);
    }//GEN-LAST:event_formMouseMoved

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if(searchInputValidator.validate_input(search_input.getText(), search_radio_buttons_group.getSelection().getActionCommand()))
            search_input.setBackground(Color.white);
        else
            search_input.setBackground(Color.orange);
    }//GEN-LAST:event_formMousePressed

    private void nip_radio_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nip_radio_buttonMouseClicked
        if(searchInputValidator.validate_input(search_input.getText(), search_radio_buttons_group.getSelection().getActionCommand()))
            search_input.setBackground(Color.white);
        else
            search_input.setBackground(Color.orange);
    }//GEN-LAST:event_nip_radio_buttonMouseClicked

    private void krs_radio_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_krs_radio_buttonMouseClicked
        if(searchInputValidator.validate_input(search_input.getText(), search_radio_buttons_group.getSelection().getActionCommand()))
            search_input.setBackground(Color.white);
        else
            search_input.setBackground(Color.orange);
    }//GEN-LAST:event_krs_radio_buttonMouseClicked

    private void regon_radio_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regon_radio_buttonMouseClicked
        if(searchInputValidator.validate_input(search_input.getText(), search_radio_buttons_group.getSelection().getActionCommand()))
            search_input.setBackground(Color.white);
        else
            search_input.setBackground(Color.orange);
    }//GEN-LAST:event_regon_radio_buttonMouseClicked

    private void nazwa_radio_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nazwa_radio_buttonMouseClicked
        if(searchInputValidator.validate_input(search_input.getText(), search_radio_buttons_group.getSelection().getActionCommand()))
            search_input.setBackground(Color.white);
        else
            search_input.setBackground(Color.orange);
    }//GEN-LAST:event_nazwa_radio_buttonMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton download_data_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton krs_radio_button;
    private javax.swing.JRadioButton nazwa_radio_button;
    private javax.swing.JRadioButton nip_radio_button;
    private javax.swing.JRadioButton regon_radio_button;
    private javax.swing.JTextField search_input;
    private javax.swing.ButtonGroup search_radio_buttons_group;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       
    }
}
